# This workflow flags issues and PRs that have gone unattended for a predetermined period of time, notifies them, and then closes them.


name: DevOps Accelerate task, mark stale issues and pull requests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
    - uses: actions/checkout@v3
    - name: List files in the repository
    - run: |
          ls ${{ github.workspace }}
    - run: echo "This job's status is ${{ job.status }}."
  
  stale:
        runs-on: ubuntu-latest
        permissions:
          issues: write
        steps:
          - uses: actions/stale@v5
            with:
              repo-token: ${{ secrets.SECRETS }}
              stale-issue-message: 'Due to the lack of activity, this issue is stale.'
              close-issue-message: 'Issue closed due to inactivity.'
              stale-issue-label: 'no-issue-activity-happening'
              days-before-issue-stale: 1
              days-before-issue-close: 2
