# This workflow flags issues and PRs that have gone unattended for a predetermined period of time, notifies them, and then closes them.


name: DevOps Accelerate task, mark stale issues and pull requests

on: [push]

jobs:
  stale:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.SECRETS }}
          stale-issue-message: 'Stale'
          days-before-issue-stale: 1
          days-before-issue-close: 2
      - name: List files in the repository
      - run: |
            ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
         
